### ISSUE TITLE
[Bug] Some Windows Accent Colors Cause Crashes

### ISSUE THREAD

**Issue by quangkieu** [Opticos/GWSL-Source#1]
I am using the Store version 1.3.6.0, even after reinstall the app, there are icon on taskbar and notification are but I do not have any windows display
Edition	Windows 10 Education
Version	20H2
Installed on	‎12/‎14/‎2019
OS build	19042.508
Experience	Windows Feature Experience Pack 120.2212.31.0

**Comment by quangkieu** [comment]
This is the error from dashboard.log

2020-09-15 16:11:01,445 - __main__ - ERROR - Exception occurred
Traceback (most recent call last):
  File "manager.py", line 3200, in <module>
  File "manager.py", line 2867, in draw
ValueError: invalid color argument
2020-09-15 16:11:01,445 - __main__ - ERROR - Exception occurred
Traceback (most recent call last):
  File "manager.py", line 3200, in <module>
  File "manager.py", line 2867, in draw
ValueError: invalid color argument

**Comment by Pololot64** [comment]
Hey @quangkieu ! Yes, I am aware of this issue and and going to push a fix in the next GWSL release. In the meantime, a workaround is to choose a different Windows 10 accent color. Sorry for the late response. I was not expecting anything outside of the Discord server.
