### ISSUE TITLE
SystemExit Exception

### ISSUE THREAD

**Issue by nicola-lunghi** [Opticos/GWSL-Source#154]
If in windows I click the Exit button I got the following exception:

```
2022-06-27 12:37:05,512 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 615, in main
SystemExit
2022-06-27 12:37:11,727 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 615, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 697, in <module>
  File "main.py", line 621, in main
SystemExit
```

**Comment by jrtokarz** [comment]
Seeing the same issue:
GWSL 1.4.0 from MS Store
Edition	Windows 10 Enterprise
Version	21H2
Installed on	‎28/‎09/‎2021
OS build	19044.1826
Experience	Windows Feature Experience Pack 120.2212.4180.0

App closed because the X server service fails.
Running 'GWSL_vcxsrv.exe' from the terminal gives the following:
```
$ ./GWSL_vcxsrv.exe
Welcome to the VcXsrv X Server
Vendor: The VcXsrv Project
Release: 1.20.9.0

OS: Windows NT 6.2 build 9200 (64-bit)
Contact: marha@users.sourceforge.net

LoadPreferences: C:\Users\Tokarz.SIT\.XWinrc not found
LoadPreferences: Loading C:\Users\Tokarz.SIT\AppData\Roaming\GWSL\VCXSRV\system.XWinrc
Segmentation fault
```

**Comment by Pololot64** [comment]
Hmm. Is this only on exit @jrtokarz ?

**Comment by jrtokarz** [comment]
@Pololot64 no, this is on starting GWSL

**Comment by hemanta212** [comment]
After the 1.4.5 update, it stopped working for me with this same issue, 

Installed through the windows store version
GWSL 1.4.5
WSL 2
Windows 11 21H2 (Build:22000.1455)

Dashboard log is empty

service log 
```
2023-01-30 14:45:05,964 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 675, in main
SystemExit
2023-01-30 14:45:06,434 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 675, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 757, in <module>
  File "main.py", line 681, in main
SystemExit
```

happy to provide with any other info

**Comment by hemanta212** [comment]
is it the settings.json file stored in the same dir as logs ? (i.e at %AppData%/GWSL/), I suppose so

http://sprunge.us/ljh8C1

```json
{
 "conf_ver": 7,
 "gwsl_ver": "1.4.5",
 "general": {
  "pulseaudio": true,
  "hide_donation_reminder": false,
  "force_disable_primary": false,
  "clipboard": true,
  "start_menu_mode": false,
  "shell_gui": "cmd",
  "acrylic_enabled": true
 },
 "graphics": {
  "window_mode": "multi",
  "hidpi": true
 },
 "putty": {
  "ip": null,
  "ssh_key": null
 },
 "distro_blacklist": [
  "docker"
 ],
 "app_blacklist": [
  "exampleblock"
 ],
 "xserver_profiles": {
  "Plain VcXsrv": []
 }
}
```

**Comment by Pololot64** [comment]
Wait. Is gwsl failing to run or are Linux apps failing to run?

**Comment by hemanta212** [comment]
It appears the gwsl is giving those errors when it starts, basically, when I run gwsl at the windows startup it appears in the tray but viewing its logs shows the above errors.  Opening wsl and running GUI apps dont work and dont add any errors to the log as well.

**Comment by Pololot64** [comment]
Can you re-verify that gwsl is allowed through the firewall? That is likely the issue. (See the manual for details or click the button in GWSL Dashboard / about )

**Comment by hemanta212** [comment]
I rechecked the firewall settings, looks like I've allowed it, for good measure I allowed all gwsl and related apps both public and private access then exited and restarted gwsl. Still does not seem to work and produce same errors in the log.

**Comment by Pololot64** [comment]
Well one thing I know is that the issue is kind of "fake" because GWSL tends to spam that error message. It generally means nothing. I can fix it but since it does not affect functionality I don't have time at the moment. 

So, just to clarify, GWSL is not crashing in any way? 

It may also be wslg conflicting with it. I would recommend disabling it to check.

**Comment by hemanta212** [comment]
ok i'll try to reinstall gwsl and also try disabling the wslg and see if it works.

**Comment by hemanta212** [comment]
Disabled wslg, reinstalled Gwsl, restarted the system but still cant make it work unfortunately

**Comment by Pololot64** [comment]
I'll do some more thinking 🤔

**Comment by Pololot64** [comment]
Are you using a VPN anywhere or anything?

**Comment by hemanta212** [comment]
no, I am not using VPN.

**Comment by hemanta212** [comment]
only thing i remember that may have effect is updating gwsl from store, otherwise I had running it fine and had no other environmental change whatsoever

**Comment by hemanta212** [comment]
when i launch an gui app through bash it does nothing just get stuck, now window pops up nothing,
exporting display to non existing port would error out so it means the connection with gwsl is there but just no window shows up by gwsl.

**Comment by Pololot64** [comment]
This is really strange. I know the xclock works so this makes it more strange. Maybe the new vcxsrv backend version has a bug. I doubt it but maybe

**Comment by hemanta212** [comment]
i tried with xclock it hunged, so left it and after some time exited with
```
Error: Can't open display: 172.28.176.1:0.0
```

**Comment by Pololot64** [comment]
Aha... this is good information. Can you ping that IP address from inside wsl? Also, is your distro wsl1 or wsl2?

**Comment by hemanta212** [comment]
its wsl2 and display was exported through the function auto inserted by GWSL in bashrc.

ping output
```
PING 172.27.176.1 (172.27.176.1) 56(84) bytes of data.
```
it then hangs

**Comment by Pololot64** [comment]
Aha. This is incredibly unrelated to the GWSL update then. I know you did it before but go into firewall settings and delete all rules related to GWSL. Something has likely gotten messed up.

**Comment by hemanta212** [comment]
ok so there were multiple entries in the firewall for GWSL VCXsrv windows server HIDPI so I removed all except one and now it worked

**Comment by Pololot64** [comment]
Awesome :)

**Comment by hemanta212** [comment]
so what was the issue? how did those entries came there in first place, was it due to update or just some coincidence?

**Comment by hemanta212** [comment]
Any way glad to have this finally sorted out and work. Thank you so much for the support here hope you have an awesome day.
btw will those deleted fpulseaudio firewall entries auto populate itself through windows firewall requests when I use them?

**Comment by Pololot64** [comment]
What happens is that sometimes, after an update, Windows detects GWSL as a new program and asks you to allow it through again. That second prompt can be easy to miss. It causes 90% percent of problems.

**Comment by Pololot64** [comment]
Yes the rules will come back when you start GWSL the next time and give public access when it gives the prompts. Glad to help. Have a wonderful day too.
