### ISSUE TITLE
Problem when building

### ISSUE THREAD

**Issue by ZreXoc** [Opticos/GWSL-Source#179]
I got error when running `build.py`
```
$ python .\build.py
Building Dashboard...
306 INFO: PyInstaller: 3.5
307 INFO: Python: 3.8.10
320 INFO: Platform: Windows-10-10.0.22631-SP0
320 INFO: wrote C:\Users\zrex\Downloads\Compressed\GWSL-Source-145\GWSL-Source-145\GWSL.spec
322 INFO: UPX is not available.
324 INFO: Extending PYTHONPATH with paths
['C:\\Users\\zrex\\Downloads\\Compressed\\GWSL-Source-145\\GWSL-Source-145',
 'C:\\Users\\zrex\\Downloads\\Compressed\\GWSL-Source-145\\GWSL-Source-145']
324 INFO: checking Analysis
324 INFO: Building Analysis because Analysis-00.toc is non existent
324 INFO: Initializing module dependency graph...
326 INFO: Initializing module graph hooks...
327 INFO: Analyzing base_library.zip ...
1617 INFO: Processing pre-find module path hook   distutils
2474 INFO: running Analysis Analysis-00.toc
2478 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\zrex\scoop\apps\anaconda3\current\App\envs\GWSL\python.exe
2631 INFO: Caching module hooks...
2634 INFO: Analyzing C:\Users\zrex\Downloads\Compressed\GWSL-Source-145\GWSL-Source-145\manager.py
2917 INFO: Processing pre-safe import module hook   win32com
3902 INFO: Loading module hooks...
3903 INFO: Loading module hook "hook-distutils.py"...
3905 INFO: Loading module hook "hook-encodings.py"...
3963 INFO: Loading module hook "hook-PIL.Image.py"...
4148 INFO: Loading module hook "hook-PIL.py"...
4150 INFO: Import to be excluded not found: 'PyQt5'
4150 INFO: Import to be excluded not found: 'FixTk'
4150 INFO: Import to be excluded not found: 'PySide'
4150 INFO: Import to be excluded not found: 'PyQt4'
4150 INFO: Excluding import 'tkinter'
4151 INFO:   Removing import of tkinter from module PIL.ImageTk
4152 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
4153 INFO: Import to be excluded not found: 'FixTk'
4153 INFO: Excluding import 'tkinter'
4154 INFO: Loading module hook "hook-pkg_resources.py"...
<string>:20: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
4537 INFO: Loading module hook "hook-pydoc.py"...
4539 INFO: Loading module hook "hook-pythoncom.py"...
4807 INFO: Loading module hook "hook-pywintypes.py"...
5000 INFO: Loading module hook "hook-sysconfig.py"...
5002 INFO: Loading module hook "hook-win32com.py"...
5060 INFO: Loading module hook "hook-xml.py"...
5172 INFO: Loading module hook "hook-_tkinter.py"...
5282 INFO: checking Tree
5321 INFO: checking Tree
5349 INFO: Looking for ctypes DLLs
5404 INFO: Analyzing run-time hooks ...
5407 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
5410 INFO: Including run-time hook 'pyi_rth_pkgres.py'
5412 INFO: Including run-time hook 'pyi_rth__tkinter.py'
5414 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
5418 INFO: Looking for dynamic libraries
5838 INFO: Looking for eggs
5838 INFO: Using Python library C:\Users\zrex\scoop\apps\anaconda3\current\App\envs\GWSL\python38.dll
5838 INFO: Found binding redirects:
[]
5843 INFO: Warnings written to C:\Users\zrex\Downloads\Compressed\GWSL-Source-145\GWSL-Source-145\build\GWSL\warn-GWSL.txt
5879 INFO: Graph cross-reference written to C:\Users\zrex\Downloads\Compressed\GWSL-Source-145\GWSL-Source-145\build\GWSL\xref-GWSL.html
5907 INFO: checking PYZ
5908 INFO: Building PYZ because PYZ-00.toc is non existent
5908 INFO: Building PYZ (ZlibArchive) C:\Users\zrex\Downloads\Compressed\GWSL-Source-145\GWSL-Source-145\build\GWSL\PYZ-00.pyz
Traceback (most recent call last):
  File ".\build.py", line 10, in <module>
    PyInstaller.__main__.run([
  File "C:\Users\zrex\scoop\apps\anaconda3\current\App\envs\GWSL\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\zrex\scoop\apps\anaconda3\current\App\envs\GWSL\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\zrex\scoop\apps\anaconda3\current\App\envs\GWSL\lib\site-packages\PyInstaller\building\build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Users\zrex\scoop\apps\anaconda3\current\App\envs\GWSL\lib\site-packages\PyInstaller\building\build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "C:\Users\zrex\Downloads\Compressed\GWSL-Source-145\GWSL-Source-145\GWSL.spec", line 18, in <module>
    pyz = PYZ(a.pure, a.zipped_data,
  File "C:\Users\zrex\scoop\apps\anaconda3\current\App\envs\GWSL\lib\site-packages\PyInstaller\building\api.py", line 98, in __init__
    self.__postinit__()
  File "C:\Users\zrex\scoop\apps\anaconda3\current\App\envs\GWSL\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "C:\Users\zrex\scoop\apps\anaconda3\current\App\envs\GWSL\lib\site-packages\PyInstaller\building\api.py", line 128, in assemble
    self.code_dict = {
  File "C:\Users\zrex\scoop\apps\anaconda3\current\App\envs\GWSL\lib\site-packages\PyInstaller\building\api.py", line 129, in <dictcomp>
    key: strip_paths_in_code(code)
  File "C:\Users\zrex\scoop\apps\anaconda3\current\App\envs\GWSL\lib\site-packages\PyInstaller\building\utils.py", line 660, in strip_paths_in_code
    return code_func(co.co_argcount, co.co_kwonlyargcount, co.co_nlocals, co.co_stacksize,
TypeError: an integer is required (got type bytes)
```

```sh
$ conda list
# packages in environment at C:\Users\zrex\scoop\apps\anaconda3\current\App\envs\GWSL:
#
# Name                    Version                   Build  Channel
altgraph                  0.17.4                   pypi_0    pypi
bzip2                     1.0.8                he774522_0
ca-certificates           2023.12.12           haa95532_0
expat                     2.5.0                hd77b12b_0
imtools                   2.0.1                    pypi_0    pypi
keyboard                  0.13.5                   pypi_0    pypi
libffi                    3.4.4                hd77b12b_0
openssl                   1.1.1w               h2bbff1b_0
pefile                    2023.2.7                 pypi_0    pypi
pillow                    10.2.0                   pypi_0    pypi
pip                       23.3.1           py38haa95532_0
psutil                    5.9.7                    pypi_0    pypi
pyinstaller               3.5                      pypi_0    pypi
pypiwin32                 223                      pypi_0    pypi
python                    3.8.10               hdbf39b2_7
pywin32                   306                      pypi_0    pypi
pywin32-ctypes            0.2.2                    pypi_0    pypi
pyxdg                     0.28                     pypi_0    pypi
setuptools                68.2.2           py38haa95532_0
sqlite                    3.41.2               h2bbff1b_0
tk                        8.6.12               h2bbff1b_0
tzdata                    2023c                h04d1e81_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.41.2           py38haa95532_0
winshell                  0.6                      pypi_0    pypi
xz                        5.4.5                h8cc25b3_0
zlib                      1.2.13               h8cc25b3_0
```
```sh
$ pip list
pip list
Package        Version
-------------- --------
altgraph       0.17.4
imtools        2.0.1
keyboard       0.13.5
pefile         2023.2.7
pillow         10.2.0
pip            23.3.1
psutil         5.9.7
PyInstaller    3.5
pypiwin32      223
pywin32        305.1
pywin32-ctypes 0.2.2
pyxdg          0.28
setuptools     68.2.2
wheel          0.41.2
winshell       0.6
```

OS: Windows11
python: 3.8.10

**Comment by Zitz19** [comment]
I got the ame problem - this is pyinstaller issue. Read this:
https://github.com/pyinstaller/pyinstaller/issues/4265
You need just to install other pyinstaller version
