### ISSUE TITLE
GWSL Service keeps crashing on Startup

### ISSUE THREAD

**Issue by J4yTr1n1ty** [Opticos/GWSL-Source#183]
On a fresh installation of the latest version from the Microsoft Store starts up, however the Service keeps crashing with the following Message: 

![image](https://github.com/Opticos/GWSL-Source/assets/41262691/84814a01-4d42-4677-bf39-71fa4826835e)

The `service.log` file lists the following Error:
```python
2024-05-28 08:38:41,816 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 663, in main
SystemExit
2024-05-28 08:38:42,797 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 663, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 757, in <module>
  File "main.py", line 681, in main
SystemExit
```

**Comment by mentalisttraceur** [comment]
I am having a silent version of this: no pop-up, but the exact same logs. (Including with fresh/reset config.)

Strangely, xclock from About in the dashboard works.

**Comment by mentalisttraceur** [comment]
Ah, looks like my version of this issue is a non-problem. After I worked around #184 everything started working for me, despite this error in the logs.

**Comment by mentalisttraceur** [comment]
Okay, now I've observed this bug, while manually fiddling. In my case, the issue was that I was launching and killing `gwsl.exe` interactively, and ending up with two instances at once (maybe one didn't get killed or was in the process of shutting down and hadn't yet let go of some lock or network port or whatever).

You can check if this is what's happening for you by seeing if there are two GWSL icons in the task bar:

![image](https://github.com/user-attachments/assets/619dabe8-fb5a-4fad-ab53-288eaeb82f4c)

One thing I noticed is that once I was in this state, hitting "yes" didn't actually fix it - since there's still two instances running, when you agree to restart, you're right back at the same problem.

If this is your situation, try hitting "No" to the restart prompt until it stops popping up, maybe also manually clear out any lingering instances in the task bar, and then start GWSL once manually.

**Comment by mentalisttraceur** [comment]
One other way I triggered this was

1. set up automatic [silent startup](https://opticos.github.io/gwsl/tutorials/manual.html#silent-startup),

2. double-clicked a `gwsl.exe --r ...` shortcut.
