### ISSUE TITLE
Issue running application after upgrade

### ISSUE THREAD

**Issue by MattFanto** [Opticos/GWSL-Source#65]
Hi, today all ubuntu application are not starting, I suppose there was an updated since I see some changes in the dashboard.
In any case while checking the logs I noticed the following message:

service.log
```
2021-05-25 14:18:42,761 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
```

I didn't make any changes to the settings file and at the same time I don't see any issue with it
```
{
 "conf_ver": 4,
 "general": {
  "clipboard": true,
  "start_menu_mode": false,
  "shell_gui": "cmd",
  "acrylic_enabled": true
 },
 "graphics": {
  "window_mode": "multi",
  "hidpi": true
 },
 "putty": {
  "ip": null,
  "ssh_key": null
 },
 "distro_blacklist": [
  "docker"
 ],
 "app_blacklist": [
  "exampleblock"
 ],
 "xserver_profiles": {
  "Plain VcXsrv": []
 }
}
```

dahsboard.log is empty instead

**Comment by Pololot64** [comment]
Huh.. Do you see any errors when you start GWSL but run the programs from bash directly?

**Comment by Pololot64** [comment]
Maybe try right clicking the systray menu --> Log and Configuration Cleanup.

Also, Dashboard --> GWSL Distro Tools --> Distro --> and export the display again.

I added audio support in this update which means it should have asked you to allow it through the firewall too. If this is being blocked by the firewall or av, it may be causing a crash. To allow it through the firewall: Dashboard --> About --> Allow GWSL through the Firewall.

**Comment by MattFanto** [comment]
Amazing it was a firewall issue it missed the permission for the public network, yes after the update it asked me the firewall config again but I forgot to add public network as well.
Thanks a million!

**Comment by Pololot64** [comment]
No problem ;) Glad it worked.

**Comment by Pololot64** [comment]
It shouldn't have made GWSL crash though so I'll see if I can quickly add some code to make it more lenient with this change

**Comment by MattFanto** [comment]
Of course and thanks a lot for this app!
Well I don't remember exactly I remember it re-asked again the permission only once and when I checked the firewall setting I noticed two entries without appropriate network access

**If I remember correctly**
Gwsl Pulseaudio didn't have any permission at all (private, domain and public)
Gwsl xcxsrv missed the public checkbox

I would say it asked the permission only for vcxsrv but I wouldn't rely too much on my limited short term memory :O

**Comment by Pololot64** [comment]
Thanks :)

**Comment by mi-hol** [comment]
looks like a knowledge base entry to me.
"audio support should have asked to allow it through the firewall too. 
If this is being blocked by the firewall or av, it may be causing a crash. 
To allow it through the firewall: Dashboard --> About --> Allow GWSL through the Firewall.
make sure pulseaudio has public access

**Comment by mi-hol** [comment]
@Pololot64 would you mind to stick to the agreed process?

**Comment by Pololot64** [comment]
Yes, but I did say that I am still extremely busy

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Pololot64** [comment]
@enterTheCloud I am assuming you pressed the auto export display button

**Comment by HuStmpHrrr** [comment]
I am experiencing the same issue. exactly the same error message. @enterTheCloud have you resolved it?

**Comment by enterTheCloud** [comment]
> @enterTheCloud I am assuming you pressed the auto export display button already?

Yes, I remember messing with that, but it didn't work either way

**Comment by enterTheCloud** [comment]
> I am experiencing the same issue. exactly the same error message. @enterTheCloud have you resolved it?

Sorry, but no. Haven't tried again since I commented
