### ISSUE TITLE
'charmap' codec can't decode byte - after ubuntu update

### ISSUE THREAD

**Issue by rabauss** [Opticos/GWSL-Source#71]
After a ubuntu update my previously running GWSL is immediately shut down after start
In the `service.log` I see the following errors - what's the solution for that problem?

````
2021-06-20 21:19:48,777 - __main__ - ERROR - Exception occurred - Cannot scan profiles
Traceback (most recent call last):
  File "main.py", line 56, in rescan
KeyError: 'xserver_profiles'
2021-06-20 21:19:53,542 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 551, in main
  File "main.py", line 494, in get_audio_running
  File "subprocess.py", line 605, in getoutput
  File "subprocess.py", line 586, in getstatusoutput
  File "subprocess.py", line 395, in check_output
  File "subprocess.py", line 474, in run
  File "subprocess.py", line 926, in communicate
  File "C:\Users\Paul-Work\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 74: character maps to <undefined>
2021-06-20 21:19:53,817 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 551, in main
  File "main.py", line 494, in get_audio_running
  File "subprocess.py", line 605, in getoutput
  File "subprocess.py", line 586, in getstatusoutput
  File "subprocess.py", line 395, in check_output
  File "subprocess.py", line 474, in run
  File "subprocess.py", line 926, in communicate
  File "C:\Users\Paul-Work\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 74: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
````

**Comment by rabauss** [comment]
Oh sorry for opening this issue - it was my soundcard driver!
Everything is fine again after driver update.

**Comment by Pololot64** [comment]
:)
