### ISSUE TITLE
GWSL force closes when it minimizes automatically

### ISSUE THREAD

**Issue by 5umm71m** [Opticos/GWSL-Source#74]
The traceback in `service.log` is as follows:
```
2021-06-26 14:09:38,853 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 551, in main
  File "main.py", line 494, in get_audio_running
  File "subprocess.py", line 605, in getoutput
  File "subprocess.py", line 586, in getstatusoutput
  File "subprocess.py", line 395, in check_output
  File "subprocess.py", line 474, in run
  File "subprocess.py", line 926, in communicate
  File "C:\Users\Paul-Work\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 74: character maps to <undefined>
2021-06-26 14:09:39,092 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 551, in main
  File "main.py", line 494, in get_audio_running
  File "subprocess.py", line 605, in getoutput
  File "subprocess.py", line 586, in getstatusoutput
  File "subprocess.py", line 395, in check_output
  File "subprocess.py", line 474, in run
  File "subprocess.py", line 926, in communicate
  File "C:\Users\Paul-Work\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 74: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
```

This error seems to have been reported in issue #71 .
It happens on a fresh installation of GWSL and Ubuntu (which currently is Ubuntu 20.04).
As long as the GWSL window stays open, GWSL works as expected but as soon as I click outside it "minimizes" and silently closes every single time.

The Windows build is `19043.1081` but it occured on earlier versions as well.
All GWSL firewall rules are allowed for private and public networks.

**Comment by 5umm71m** [comment]
I just had an idea, GWSL seems to expect a microphone to be present.

The issue only occurs if NO microphone is connected to the machine.
If I connect a USB headset, GWSL works as expected.

**Comment by Pololot64** [comment]
Strange.. I do not really know the inner workings of pulseaudio but I'm glad you at least found a workaround. I will make a switch to turn off audio probably so that it is optional on more problematic setups maybe.
