### ISSUE TITLE
GWSL 1.3.9 (store) 1654 TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by cuonghuunguyen** [Opticos/GWSL-Source#83]
I upgraded into GWSL 1.3.9 today and all the apps on my WSL cannot start.

Distribution: Ubuntu-18.04
Windows version: 20H2 build 19042.1110
GWSL 1.3.9

Logs:
```
2021-06-05 18:43:13,200 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-06-05 18:43:13,664 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-06-08 11:37:41,366 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-06-08 11:37:41,783 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-06-09 21:03:29,052 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-06-09 21:03:29,965 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-06-14 17:29:51,683 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-06-14 17:29:52,299 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-06-16 17:46:41,983 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-06-16 17:46:42,370 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-06-17 19:11:31,503 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-06-17 19:11:31,956 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-06-18 20:04:11,119 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-06-18 20:04:12,123 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-06-22 18:08:11,400 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-06-22 18:08:11,859 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-06-23 19:30:30,953 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-06-23 19:30:31,451 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-06-24 19:56:49,104 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-06-24 19:56:50,108 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-06-28 18:26:56,475 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-06-28 18:26:57,034 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-06-29 14:34:16,174 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-06-29 14:34:16,810 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-06-29 18:37:25,982 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-06-29 18:37:26,787 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-07-05 11:41:18,958 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-07-05 11:41:19,464 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-07-05 17:19:33,430 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-07-05 17:19:33,966 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-07-05 18:51:02,608 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-07-05 18:51:03,111 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-07-07 14:03:03,274 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-07-07 14:03:03,860 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-07-07 14:09:02,426 - __main__ - ERROR - Exception occurred - Cannot Start VcXsrv
Traceback (most recent call last):
  File "main.py", line 474, in start_server
  File "subprocess.py", line 775, in __init__
  File "subprocess.py", line 1178, in _execute_child
OSError: [WinError 15616] The application cannot be started because it is currently updating
2021-07-07 21:12:10,720 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-07-07 21:12:11,189 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-07-13 16:53:33,116 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-07-13 16:53:33,545 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-07-15 19:25:20,950 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-07-15 19:25:21,354 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-07-20 18:12:47,574 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-07-20 18:12:48,060 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-07-23 19:23:49,425 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-07-23 19:23:50,358 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-07-26 19:11:28,805 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-07-26 19:11:29,440 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-07-26 19:12:07,907 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-07-26 19:12:08,522 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-07-27 10:55:39,972 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-07-27 10:55:40,439 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-07-27 13:17:34,276 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-07-27 13:17:34,754 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-07-27 19:27:57,581 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-07-27 19:27:58,048 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-07-29 13:48:42,009 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit
2021-07-29 13:48:42,456 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 561, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 642, in <module>
  File "main.py", line 567, in main
SystemExit
2021-08-03 10:29:06,497 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 594, in main
SystemExit
2021-08-03 10:29:06,980 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 594, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 675, in <module>
  File "main.py", line 600, in main
SystemExit
2021-08-03 10:29:39,035 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 594, in main
SystemExit
2021-08-03 10:29:39,480 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 594, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 675, in <module>
  File "main.py", line 600, in main
SystemExit
2021-08-03 14:35:28,719 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 594, in main
SystemExit
2021-08-03 14:35:29,219 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 594, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 675, in <module>
  File "main.py", line 600, in main
SystemExit
2021-08-03 14:37:11,469 - __main__ - ERROR - Exception occurred - Cannot Start VcXsrv
Traceback (most recent call last):
  File "main.py", line 481, in start_server
  File "subprocess.py", line 800, in __init__
  File "subprocess.py", line 1207, in _execute_child
OSError: [WinError 15616] The application cannot be started because it is currently updating
```

**Comment by cuonghuunguyen** [comment]
Dashboard.log
```
2021-08-03 14:36:37,116 - GWSL 1.3.9 - ERROR - Exception occurred - Error in Mainloop
Traceback (most recent call last):
  File "manager.py", line 4335, in <module>
  File "manager.py", line 3974, in draw
  File "manager.py", line 3917, in setter
  File "manager.py", line 1900, in configure_machine
  File "manager.py", line 1654, in indirect_conf
TypeError: can only concatenate str (not "NoneType") to str
```
