### ISSUE TITLE
Windows service crash

### ISSUE THREAD

**Issue by dsoundmn** [Opticos/GWSL-Source#92]
I've been having this crash on my system (even with AV disabled) Any suggestions?

Edition	Windows 10 Enterprise
Version	21H1
Installed on	‎5/‎5/‎2021
OS build	19043.1165
Experience	Windows Feature Experience Pack 120.2212.3530.0

![image](https://user-images.githubusercontent.com/1131489/131399913-00685c12-34f8-4937-be1c-ffe31728e658.png)

2021-08-30 16:09:07,160 - __main__ - ERROR - Exception occurred in main loop
Traceback (most recent call last):
  File "main.py", line 603, in main
SystemExit
2021-08-30 16:09:07,552 - __main__ - ERROR - Exception occurred - Cannot Start Service. Make sure the settings file is not corrupted.
Traceback (most recent call last):
  File "main.py", line 603, in main
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 697, in <module>
  File "main.py", line 621, in main
SystemExit

**Comment by dsoundmn** [comment]
It's also worth noting that I receive this on all builds even after a clean install (uninstall and wipe roaming folder)

**Comment by Pololot64** [comment]
It is vcxsrv crashing so it has possibly made its own log. Change the GWSL profile to "Plain VCXSRV" and wait for the vcxsrv systray to appear alongside GWSL's (it is the same except for the black text "xserver"). Right click it and show logs. I do not know too much about it's inner workings but it may shed some light on the situation.

**Comment by dsoundmn** [comment]
I'm guessing that too - but I only get errors for the plain session. I'll keep this updated.

**Comment by dsoundmn** [comment]
@Pololot64 I've finally figured out what occurred. We also run a security service that for some unknown reason uses the 0:0 port for their instance of Postgres, that being said. This is clearly not a bug on your end.

However, why is vcxsrv so picky that it doesn't fail gracefully? Is this something we could capture and display back to end-users? - Feature request!!! 

thank you for your help - it got the answer.

**Comment by Pololot64** [comment]
Vcxsrv can close gracefully but I believe k am passing a flag to suppress error messages. It would crash and then make a pop-up. (I have not looked at the code in a while but that is why it is quitting like that). If it does crash catastrophically it is some bug in vcxsrv that I am not aware of.

**Comment by Pololot64** [comment]
Actually since you are doing a custom profile it is not suppressing anything. So it must be a vcxsrv bug that makes it crash. Or not even start if the port is already used.
